### ISSUE TITLE
Lesson2. Convert

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#1]
1.  Все методы вызовите из main
2. Имена методов должны быть с маленькой буквы
3. ToShort(String[] args) - если параметр метода не используется в самом методе, он не нужен. Уберите его. И в остальных методах  тоже
4. К char можно привести из остальных числовых типов тоже.
5. К float и double тоже

**Comment by Kashalol** [comment]
Сделал, но немного изменилось расположение д/з. Причесал относительно расположения заданий на сайте.
