### ISSUE TITLE
Car

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#14]
1. Engine,Driver ,Person- добавить модиф. доступа переменным.
2. Driver - добавьте переменную метода drivingExperience:
```
   public Driver(String fullName) {
        super(fullName);
        this.drivingExperience = drivingExperience;
    }
```
3. Создать объекты класса Lorry и SportCar.
4. Класс PersonUsage переименуйте в Person. Сделайте его public

**Comment by Kashalol** [comment]
1. Добавил.
2. Такой конструктор у меня был.
3. Создал и использовал.
4. Поубирал лишние *Usage во всех названиях. И вынес CarDemo отдельно

**Comment by milkina** [comment]
Пункт 2 - конструктор должен быть такой:
```
   public Driver(String fullName,int drivingExperience) {
        super(fullName);
        this.drivingExperience = drivingExperience;
    }
```

**Comment by Kashalol** [comment]
Исправил. Пардон за невнимательность.
