### ISSUE TITLE
Animal

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#16]
1.  Напишите реализацию для методов makeNoise, eat, sleep в классе Animal. Или сделайте их абстрактными. Например вывести на консоль: такое-то животное спит.
2. VetDemo - если можно использовать метод for each вместо for,  используйте его.

**Comment by Kashalol** [comment]
Может просто override сделать внутри каждого из наследующих классов? А в Animal оставить пустыми? 
Да и abstract мы на том уроке ещё не учили.

**Comment by milkina** [comment]
Ну, уже ж выучили. Делафйте абстрактным. Пустым ни в коем случае нельзя оставлять.

**Comment by Kashalol** [comment]
Исправил. Повызывал
