### ISSUE TITLE
Flower

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#17]
1. Сделать Flower public
2. Имя пакета с маленькой буквы -NotCarHomework
3. Методы equals, hashCode, toString добавить в каждый класс.
4.  bouquetPrice - перенесите в класс Flower.
5. Вместо
```
      for (int i = 0; i < bouquet.length; i++) {
            priceOfBouquet += bouquet[i].getPrice();
            if (i == bouquet.length - 1) {
                System.out.println("Цена букета составляет : " + priceOfBouquet);
            }
        }
```
можно:
```
        for (int i = 0; i < bouquet.length; i++) {
            priceOfBouquet += bouquet[i].getPrice();
        }
        System.out.println("Цена букета составляет : " + priceOfBouquet);
```
6.   static int flowersSold; перенести в Flower и считать количество в конструкторе.

**Comment by Kashalol** [comment]
1. Сделал.
2. Перенес в пакет flowerBouquet.
3. Добавил.
4. А смысл? 
5. Исправил.
6. И снова тот же вопрос - смысл? Набить класс flower ненужными там переменными и перетащить их в наследующие классы?

**Comment by milkina** [comment]
4. bouquetPrice  работает с цветами. Исходя из принципа инкапсуляции он должен находиться там. Класс FlowerDemo является клиентом, который просто создает цветы. Таких клиентов может быть много.  Может быть какой-то вебсервис будет сработать с Flower. 

5.  Смысл тот же . Перетаскивать в другие классы здесь как раз ничего не надо.

**Comment by Kashalol** [comment]
Исправил оба пункта.

**Comment by milkina** [comment]
static int flowersSold; - считайте количество в конструкторе. Пример - класс Ball.

**Comment by Kashalol** [comment]
В классе Ball он считает количество созданных объектов. А у нас задача стояла посчитать общее количество проданных цветов. А это насколько я понимаю общее количество цветов в трёх букетах (массивах).

**Comment by milkina** [comment]
Ну, ок - уговорили.
Ну будущее изменю задание.
