### ISSUE TITLE
Fruit

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#19]
1.  Все классы- добавить мод. доступа переменным.
2. printManufacturerInfo -добавить мод. доступа. Вызвать его.
3. Вместо
```
 @Override
    double priceReturn(double weight) {
        double result = applePrice * weight;
        return result;
    }
```
можно
```
@Override
    double priceReturn(double weight) {
        return  applePrice * weight;
    }
```
4. FruitStoreDemo - неотформатировано
5. Вместо apllesSumm,pearSumm и apricotSumm cделайте один метод:
```
    public static double fruitsSumm(Fruit... fruits) {
        double result = 0;
        for (Fruit fruit: fruits) {
            result += fruit.priceReturn(fruit.getWeight());
        }
        return result;
    }
```
И перенесите его в Fruit.

**Comment by Kashalol** [comment]
1. Добавил.
2. Добавил. Вызвал для разных объектов.
3. Исправил.
4. Отформатировал.
5. Сделал общий метод. Перенес в Fruit
