### ISSUE TITLE
Lesson 3. Adding2

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#2]
1. Используйте один объект класса Scanner

**Comment by Kashalol** [comment]
А как мне в таком случае проверить что оба введёных числа корректны не городя при этом if в if?

**Comment by milkina** [comment]
Создайте метод, в кот. перенесите:
 System.out.println("Введите  целое число");
        if (sc1.hasNextInt() ) {
            int i1 = sc1.nextInt();
         } else {
            System.out.println("Ошибка ввода");
        }

**Comment by Kashalol** [comment]
Исправил

**Comment by milkina** [comment]
1. Scanner sc1 = new Scanner(System.in); пишите в main И передавайте в метод
2. А вот int i уберите из параметров метода.

**Comment by Kashalol** [comment]
То есть sc1 оставлять в main. Тут же проверяем его на hasNextInt. Передаем это значение в локальную int переменную. И уже эту переменную мы передаем в метод?

**Comment by Kashalol** [comment]
Исправил
