### ISSUE TITLE
Lesson 3.  Module

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#3]
1. Перед sc1.nextDouble();  вызовите hasNextDouble()
2. Следующий блок кода вынесите в отд. метод, который будет вызываться три раза:
       System.out.println("Введите первое вещественное число");
        double d1 = sc1.nextDouble();
        d1 = d1 < 0 ? -d1 : d1;
3.
Вместо
  if ((d1 < d2) && (d1 < d3)) {
            System.out.println("Наименьшее число по модулю " + d1);
        } else {
            if ((d2 < d3) && (d2 < d1)) {
                System.out.println("Наименьшее число по модулю " + d2);
            } else {
                System.out.println("Наименьшее число по модулю " + d3);
            }
        }

лучше:
        if (d1 < d2 && d1 < d3) {
            System.out.println("Наименьшее число по модулю " + d1);
        } else if (d2 < d3 && d2 < d1) {
            System.out.println("Наименьшее число по модулю " + d2);
        } else {
            System.out.println("Наименьшее число по модулю " + d3);
        }

**Comment by Kashalol** [comment]
Сделал, но немного изменилось расположение д/з. Причесал относительно расположения заданий на сайте.

**Comment by milkina** [comment]
1. Перед sc1.nextDouble(); вызовите hasNextDouble()
2. Scanner sc1 = new Scanner(System.in); вынесите в main  и передавайте его в метод.

**Comment by Kashalol** [comment]
Исправил. Буду стараться внимательней читать Ваши замечания и бороться со своей торопыжливостью.
И if ((d1 < d2) && (d1 < d3)) заменить на if (d1 < d2 && d1 < d3) нельзя. IDEA сразу ругается и требует общие скобки

**Comment by milkina** [comment]
1. hasNextDouble() надо вызывать перед каждым hasNextDouble(). Короче метод должен выглядеть как-то так:
    public static double inputDouble(Scanner sc1) {
        if (sc1.hasNextDouble()) {
            double dInput = sc1.nextDouble();
            dInput = dInput < 0 ? -dInput : dInput;
            return dInput;
        } else {
            System.out.println("Ошибка ввода");
            return 0;
        }
    }
2. if (d1 < d2 && d1 < d3)  должно работать!

**Comment by Kashalol** [comment]
1. Исправил. Проверка после введения каждого числа теперь. И понял зачем это нужно.
2. Перезагрузил IDEA и перестало ругаться. Непонятно чего оно так было, наверное бури на Солнце.

**Comment by milkina** [comment]
Все отлично, но  Scanner sc1 = new Scanner(System.in); пишите в main И передавайте в метод

**Comment by Kashalol** [comment]
Исправил
