### ISSUE TITLE
lesson3. Garland

### ISSUE THREAD

**Issue by milkina** [Kashalol/Upload#4]
1. Используйте один объект класса Scanner, созданный в методе main. В остальные методы передавайте его.
2. Перед вызовом  int i1 = sc1.nextInt(); вызовите hasNextInt.
3. Создайте отдельный метод, который будет выводить на консоль состояние вашей гирлянды.
4. В методе firstLamp используйте побитовую операцию &.
5.

**Comment by Kashalol** [comment]
1. Сделал
2. Сделал для ввода числа для гирлянды, но в некоторых методах оставил второй для возможности задавать количество итераций
3. Он и так есть под номером 5, он же garlandState
4. Сделал

**Comment by milkina** [comment]
1. Ok
2. Передавайте sc1 из main. И можно тоже вынести в отд. метод.
3. Ну так вызывайте его.
4. Ok.
Напомните  на уроке - обсудим

**Comment by Kashalol** [comment]
2) Исправил.
3) Вызывается 5 в выборе режима.
обсудили

**Comment by milkina** [comment]
1.               String trans = Integer.toBinaryString(i1);
                addingZero(trans);
                System.out.println(trans);
Повторяется 3 раза - создайте метод printState и перенесите туда эти строки.

2. По поводу переменных i1,i2,i3,i4 - выбирайте более понятные имена. Мы ж это вроде несколько раз обсуждали.

**Comment by Kashalol** [comment]
Даже 4 раза повторялось. Поправил.
Переменные поправил.
С каждой итерацией правок по вашим замечаниям код становится все лучше и лучше)

**Comment by milkina** [comment]
А то! Но нет пределу совершенству, поэтому:
1.  В методы switching, movingLeft, movingRight можно тоже передавать объект класса Scanner.
2.  Комментарии к методам оформите в виде документирующих комментариев:
Вместо //метод для миганий гирлянды
лучше:
/**
** Метод для миганий гирлянды
...

**Comment by Kashalol** [comment]
1. А какой смысл? Я изначально Scanner превратил в int и передаю его в методы. А иначе мне придется в каждом методе это делать отдельно
2. Пробовал комменты и забыл удалить просто. Убрал совсем чтобы не захламлять.

**Comment by Kashalol** [comment]
Исправил

**Comment by milkina** [comment]
Уррра!!!!!!!!!!!!!!!
